### ISSUE TITLE
Clean up WNTR and EPANET files after simulation has completed

### ISSUE THREAD

**Issue by tasseff** [NREL-SIIP/WaterModelsAnalytics.jl#14] opened 2020-11-05 18:57 UTC
Currently, `.inp`, `.bin`, and `.rpt` files are written upon running an EPANET simulation but are not deleted after completion.

**Comment by tasseff** [comment] 2020-11-05 19:02
Also, ensure that EPANET files are written to a temporary folder, e.g., `/var/tmp` with unique names instead of in the directory that the package is run. I assume that Julia has a function that creates and returns the path for a temporary directory.

**Comment by enzoliuyang94** [comment] 2020-11-06 05:05
I tried to implement this, but it turned out that the path to which the temporary inp file is saved cannot be specified - the user can only change the name of this file, not the its location. However, since now we know what causes the segrementation error and the issue is resolved, we no longer need to create temporary inp files with different names (using random numbers), so there should be at most one temporary inp file at any time.

**Comment by tasseff** [comment] 2020-11-06 18:35
@enzoliuyang94, can't `file_prefix` in WNTR's `run_sim` be an absolute path to a temporary directory? These names and directories should be randomized for future thread safety and cleaned up afterward.

**Comment by tasseff** [comment] 2020-11-06 18:41
I just confirmed that using something like
```python3
results = sim.run_sim(file_prefix='/var/tmp/tmp123')
```
indeed places the input/output files into `/var/tmp/`, creating `tmp123.bin`, `tmp123.rpt`, and `tmp123.inp` in that directory. We should be able to create a random directory, specify this random directory (and a prefix for the filename) in `file_prefix`, then clean up the simulation files after the simulation has completed.

**Comment by enzoliuyang94** [comment] 2020-11-06 18:43
@tasseff Ok, will implement this now. Thanks

**Comment by jjstickel** [comment] 2020-11-06 18:56
You can use `mktmpdir` to create a temporary folder. I think this uses some information about the OS to put the temp directory in an expected place on the filesystem. See some example usage here:

https://github.com/NREL-SIIP/WaterModelsAnalytics.jl/blob/master/test/graph.jl

**Comment by enzoliuyang94** [comment] 2020-11-06 18:58
@jjstickel Thanks! I was just googling and find something very similiar. Implementing this right now.

**Comment by jjstickel** [comment] 2020-11-10 15:27
Resolved with #23

**Closed by jjstickel** 2020-11-10 15:27 UTC
